"""initial migration

Revision ID: 138eb10561d7
Revises: 57e624d03779
Create Date: 2014-09-23 11:00:39.938290

"""

# revision identifiers, used by Alembic.
revision = '138eb10561d7'
down_revision = '57e624d03779'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
