"""initial migration

Revision ID: 158ee6006503
Revises: None
Create Date: 2014-09-29 08:32:45.344401

"""

# revision identifiers, used by Alembic.
revision = '158ee6006503'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
