"""inital imgration

Revision ID: 15f3e42b5700
Revises: 1aeb1da9c0cb
Create Date: 2014-09-24 14:13:11.096668

"""

# revision identifiers, used by Alembic.
revision = '15f3e42b5700'
down_revision = '1aeb1da9c0cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###
