"""inital imgration

Revision ID: 1aeb1da9c0cb
Revises: 4d732125ed9d
Create Date: 2014-09-24 08:44:41.899072

"""

# revision identifiers, used by Alembic.
revision = '1aeb1da9c0cb'
down_revision = '4d732125ed9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
