"""initial migration

Revision ID: 2e5256d84a5e
Revises: 138eb10561d7
Create Date: 2014-09-23 14:58:44.113773

"""

# revision identifiers, used by Alembic.
revision = '2e5256d84a5e'
down_revision = '138eb10561d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'avatar_hash')
    ### end Alembic commands ###
