"""initial migration

Revision ID: 35fbbaf8b3f
Revises: 2e5256d84a5e
Create Date: 2014-09-23 15:45:55.151044

"""

# revision identifiers, used by Alembic.
revision = '35fbbaf8b3f'
down_revision = '2e5256d84a5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
