"""initial migration

Revision ID: 3bf995224834
Revises: 51ca71e8baff
Create Date: 2014-09-25 10:00:45.906203

"""

# revision identifiers, used by Alembic.
revision = '3bf995224834'
down_revision = '51ca71e8baff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
