"""initial migration

Revision ID: 4d732125ed9d
Revises: 35fbbaf8b3f
Create Date: 2014-09-23 16:05:45.238693

"""

# revision identifiers, used by Alembic.
revision = '4d732125ed9d'
down_revision = '35fbbaf8b3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
