"""initial migration

Revision ID: 4deea3a752a7
Revises: 158ee6006503
Create Date: 2014-09-30 08:30:36.205175

"""

# revision identifiers, used by Alembic.
revision = '4deea3a752a7'
down_revision = '158ee6006503'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
