"""initial migration

Revision ID: 51ca71e8baff
Revises: 15f3e42b5700
Create Date: 2014-09-25 08:35:50.075566

"""

# revision identifiers, used by Alembic.
revision = '51ca71e8baff'
down_revision = '15f3e42b5700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
