"""initial migration

Revision ID: 57e624d03779
Revises: cd573a13acf
Create Date: 2014-09-23 10:45:44.201975

"""

# revision identifiers, used by Alembic.
revision = '57e624d03779'
down_revision = 'cd573a13acf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
