"""initial migration

Revision ID: cd573a13acf
Revises: None
Create Date: 2014-09-23 10:19:27.635928

"""

# revision identifiers, used by Alembic.
revision = 'cd573a13acf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
